# Generated by Django 6.0.3 on 2026-03-23 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('direction', models.CharField(choices=[('IT', 'IT'), ('Media', 'Медиа'), ('Social', 'Социальное проектирование')], max_length=20, verbose_name='Направление')),
                ('base_points', models.PositiveIntegerField(default=10, verbose_name='Базовые баллы')),
                ('difficulty_coef', models.FloatField(default=1.0, verbose_name='Коэффициент сложности')),
                ('bonus_text', models.CharField(blank=True, max_length=255, verbose_name='Бонусы')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. участников')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
        ),
    ]
