# Generated by Django 6.0.3 on 2026-03-23 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('attended', 'Присутствовал'), ('confirmed', 'Подтвержден')], default='registered', max_length=20, verbose_name='Статус')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Начисленные баллы')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_participations', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Мероприятие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участие в мероприятии',
                'verbose_name_plural': 'Участия в мероприятиях',
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
